version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.23
    restart: always
    ports:
      - "4466:4466"
    env_file: .env
    environment:
      PRISMA_CONFIG: |
        port: PRISMA_PORT
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: ${POSTGRES_USER}
            password: ${POSTGRES_PASSWORD}
            migrations: true
  postgres:
    image: postgres:10.5
    restart: always
    ports:
      - "5432:5432"
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
